### ISSUE TITLE
Does this lib support jwks_uri?

### ISSUE THREAD

**Issue by Clee681** [Dan6erbond/sk-auth#28]
Hello,

For cases where the authorization server rotates the JWT keys (e.g. [Okta](https://developer.okta.com/docs/concepts/key-rotation/#key-rotation-for-custom-authorization-servers)), does this lib support fetching keys from a `jwks_uri`?

**Comment by Dan6erbond** [comment]
Hey, please bring these issues to the [GitHub Discussions](https://github.com/Dan6erbond/sk-auth/discussions) of this project.

But yes, refreshing tokens shouldn't be an issue. You can manage this process in the `token()` callback similar to the way it's described in the [NextAuth.js documentation](https://next-auth.js.org/tutorials/refresh-token-rotation).
