### ISSUE TITLE
`request.path` has been replaced by `request.url.pathname`

### ISSUE THREAD

**Issue by krg-digital** [Dan6erbond/sk-auth#59]
I'm getting this error when calling the `signIn()` function using the latest version of SvelteKit.

**Comment by Kelvijn** [comment]
Same, related to https://stackoverflow.com/questions/70534899/sveltekit-error-request-query-has-been-replaced-by-request-url-searchparams

**Comment by Kelvijn** [comment]
@krg-digital looks like the author is not very active, have you found a workaround yet?

**Comment by krg-digital** [comment]
> Same, related to https://stackoverflow.com/questions/70534899/sveltekit-error-request-query-has-been-replaced-by-request-url-searchparams

Yeah, stumbled upon that thread when investigating the error. I'm definitely no expert when it comes to the inner-workings of SvelteKit, but I'd guess [these lines of code](https://github.com/Dan6erbond/sk-auth/blob/731eabd893f29df64870beb7ce65282312852da0/app/src/hooks.ts#L5-L8) is where the issues lies... and that `TODO` might hint at what needs to be done?

**Comment by Dan6erbond** [comment]
Hey everyone! Sorry for the inactivity, SK-Auth has now been upgraded to v0.4.0 thanks to #58 by @lulzneko which should resolve these issues.
