### ISSUE TITLE
Breaking change in sveltekit 

### ISSUE THREAD

**Issue by HalfdanJ** [Dan6erbond/sk-auth#68]
An update has been made to sveltekit (not 100% sure which version it came with) that breaks the library. This is the breaking PR: https://github.com/sveltejs/kit/pull/3384 

The error message is `event.headers has been replaced by event.request.headers. See https://github.com/sveltejs/kit/pull/3384 for details` pointing to this chunk of code: 

```
this.getSession = async ({ headers }) => {
      const token = await this.getToken(headers);
      if (token) {
        if (this.config?.callbacks?.session) {
          return await this.config.callbacks.session(token, { user: token.user });
        }
        return { user: token.user };
      }
      return {};
    };
```

I believe that instead of `{ headers }` it should be `{ request }`, and then `request.headers`. 

I tried modifying the library to make a PR, but having issues building the library in a way that the app will accept it.

**Comment by ximus** [comment]
endpoints also need updating

**Comment by orefalo** [comment]
looks like this commit from @landongn carries all the required fixes. can't wait for it to be merged.
https://github.com/landongn/sk-auth/commit/dfcd60768a938717eb33aec2d034d919e52e70cd

**Comment by Dan6erbond** [comment]
#69 was now merged with main and I'll be creating a release soon to address these breaking changes. Thanks to the help by @landongn!
