### ISSUE TITLE
ReferenceError: mergePath is not defined

### ISSUE THREAD

**Issue by vhscom** [Dan6erbond/sk-auth#74]
The library throws an error when attempting to run `signOut` in version `0.4.1`. It seems `mergePath` didn't make it into the `client` bundle. Here's a workaround: https://github.com/vhscom/svelte-headlessui-starter/blob/trunk/src/routes/account/signout.ts

**Comment by ar4hc** [comment]
if i don't miss some js black magic here, i think in `client/signIn.ts` and `signOut.ts` this import is missing:

```js
import { mergePath } from "./helpers";
```
and helpers does not export the `mergePath` function:
```js
export function mergePath(basePaths: (string | null)[], path: string) {
```

**Comment by vhscom** [comment]
@ar4hc there's a pull to resolve this in #75

**Comment by ar4hc** [comment]
> @ar4hc there's a pull to resolve this in #75

Found that after i made my comment... :( sry for the noise.

**Comment by vhscom** [comment]
Maybe some of your magic could be used to improve the pull? Haven't looked but wanted to point it out. 🙂
