### ISSUE TITLE
Verify oauth token?

### ISSUE THREAD

**Issue by mobilars** [Dan6erbond/sk-auth#87]
Hi. Does this library verify the OAuth JWT tokens for me (towards a standard keycloak oauth server) or do I need to do that myself? Verification of the issuer, signature of the JWT etc.

Best regards,
Lars

**Comment by Dan6erbond** [comment]
Hey, thanks for the question! Currently this library doesn't handle much more than the token exchange from the OAuth2 provider to the server. If you want to verify the token, you can use the callbacks to do so.

Hope this helps!
