### ISSUE TITLE
Allow setting of "redirect_uri" 

### ISSUE THREAD

**Issue by websocket98765** [Dan6erbond/sk-auth#95]
`sk-auth` defaults to `https://localhost:3000/api/auth/callback/github` with no ability to change it successfully.

Note the `s` in https.

This is problematic because for localtesting where `https` isn't used.

**Comment by moreorover** [comment]
The protocol can be set when creating a SvelteKitAuth object.

`export const appAuth: SvelteKitAuth = new SvelteKitAuth({
	providers: [oauthProvider],
	protocol: 'http'
});`

**Comment by websocket98765** [comment]
Thank you! I did the following

```js
import { dev } from '$app/env';

export const appAuth = new SvelteKitAuth({
  protocol: dev ? 'http' : 'https',
  providers: [
    // ...
  ],
  // ...
});
```
