### ISSUE TITLE
signIn/signOut broken due to SvelteKit update

### ISSUE THREAD

**Issue by leovoon** [Dan6erbond/sk-auth#99]
Recent sveltekit updates break endpoints https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

**Comment by leovoon** [comment]
#100 A PR to fix this issue.

**Comment by caiges** [comment]
@leovoon is signout working against these new changes? I'm using the main branch of sk-auth and seeing HTTP 405 on `POST http://localhost:3000/api/auth/signout` and an accompanying error:

`Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

I'll have to take a deeper look myself.

**Comment by leovoon** [comment]
> @leovoon is signout working against these new changes? I'm using the main branch of sk-auth and seeing HTTP 405 on `POST http://localhost:3000/api/auth/signout` and an accompanying error:
> 
> `Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
> 
> I'll have to take a deeper look myself.

I have no issues with it. As the PR has been merged, I might as well close this issue. You may open one of your own.

**Comment by caiges** [comment]
I had aliased `get` and `post` imports from `SvelteKitAuth` due to changes in SvelteKit which were addressed with the merge. 🥂 thanks for that fix.
